# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(278, 252)
        MainWindow.setStyleSheet("background: #20c2e3;")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generator = QtWidgets.QLabel(self.centralwidget)
        self.generator.setGeometry(QtCore.QRect(60, 10, 111, 21))
        self.generator.setStyleSheet("color: White;\n"
"background: purple;\n"
"border: 2px solid white;\n"
"border-radius: 10px;\n"
"")
        self.generator.setObjectName("generator")
        self.Pasrot = QtWidgets.QLabel(self.centralwidget)
        self.Pasrot.setGeometry(QtCore.QRect(90, 80, 61, 21))
        self.Pasrot.setStyleSheet("color: White;\n"
"background: purple;\n"
"border: 2px solid white;\n"
"border-radius: 10px;\n"
"")
        self.Pasrot.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.Pasrot.setObjectName("Pasrot")
        self.puck = QtWidgets.QPushButton(self.centralwidget)
        self.puck.setGeometry(QtCore.QRect(70, 150, 101, 31))
        self.puck.setStyleSheet("color: White;\n"
"background: purple;\n"
"border: 2px solid white;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.puck.setObjectName("puck")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 278, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор паролів"))
        self.generator.setText(_translate("MainWindow", "Генератор Паролів "))
        self.Pasrot.setText(_translate("MainWindow", " Пароль"))
        self.puck.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
